{{ if .Values.ingressEnabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
spec:
  rules:
  - host: {{ .Values.ingressHost }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}
          servicePort: {{ .Values.servicePort }}
{{ end }}
