apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}

spec:
  type: {{ .Values.serviceType }}
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.deployPort }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
